### ISSUE TITLE
Feature Request - Field to enter particular geo-fence in GUI

### ISSUE THREAD

**Issue by satyamzhcet** [iSPIRT/NPNT-Provisional-testing-tool#1]
At the moment, all the geo-fence points are static and hard-coded in the application. This will inhibit testing the drone feature of geo-fence breach at the particular provisional test site. It would be good to provide fields where user can enter latitude and longitude of the test site.

**Comment by mnihalm** [comment]
This is possible. Will work on it soon.

**Comment by sidd-shetty** [comment]
This has been implemented in the test tool. You can define your own lat long details of the test area.
