### ISSUE TITLE
NPNT complaince Applying Procedure?

### ISSUE THREAD

**Issue by yogananda72** [iSPIRT/NPNT-Provisional-testing-tool#11]
where to apply for NPNT compliance certification . can you provide sufficient information which organization to apply?

**Comment by sidd-shetty** [comment]
For India, you will have to apply to the Directorate General of Civil Aviation (DGCA). Please read Chapter 8 and Chapter 9 of the RPAS Guidance Manual for more details: http://www.dgca.nic.in/rpas/DGCA%20RPAS%20Guidance%20Manual.pdf

**Comment by yogananda72** [comment]
As per document , Certifying agency will verify the NPNT compliance
![pic1](https://user-images.githubusercontent.com/10249840/59771050-a3280680-92c6-11e9-9eea-e544ef72b8fd.PNG)
. Can you tell which agency will verify?
