### ISSUE TITLE
NPNT complaince Applying Procedure? 

### ISSUE THREAD

**Issue by yogananda72** [iSPIRT/NPNT-Provisional-testing-tool#12]
Sorry for raising same thread again. As per chapter 8, Certifying agency will verify the NPNT compliance
![pic1](https://user-images.githubusercontent.com/10249840/59771246-f601be00-92c6-11e9-8994-e305c50deebf.PNG)
. Can you tell which agency will verify the NPNT compliance?

**Comment by abrbhat** [comment]
I suggest you post this on the Digital Sky Forum https://digitalsky.ispirt.in/t/welcome-to-the-digital-sky-forum/7 since Github issue tracker is mostly for issues related to the repository.
